---
- name: run the playbook tasks on the localhost
  hosts: local
  connection: local
  vars:
    applications:
      - awscli
      - curl
      - direnv
      - docker
      - docker-compose
      - fdupes
      - gh
      - git
      - git-flow
      - go
      - htop
      - httpie
      - hugo
      - jq
      - minikube
      - neovim
      - nvm
      - rbenv
      - rclone
      - rsync
      - rustup
      - terraform
      - tmux
      - tree
      - vim
      - watchman
      - wget
      - yarn
      - zsh
    cask_applications:
      - anki
      - aws-vault
      - balenaetcher
      - calibre
      - docker
      - firefox
      - google-chrome
      - iterm2
      - jetbrains-toolbox
      - ngrok
      - notion
      - rstudio
      - skype
      - slack
      - spotify
      - surfshark
      - transmission
      - visual-studio-code
      - vlc
      - whatsapp

  tasks:
    - name: install homebrew
      shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      args:
        creates: /usr/local/bin/brew

    - name: ensure homebrew is updated
      homebrew:
        state: latest
        update_homebrew: yes

    - name: start installing homebrew applications
      homebrew:
        name: "{{applications}}"
        state: latest

    - name: start installing homebrew cask applications
      homebrew_cask:
        name: "{{cask_applications}}"
        state: upgraded
