---
- name: run the playbook tasks on the localhost
  hosts: local
  connection: local
  vars:
        - applications:
            - htop
            - awscli
            - gradle
            - maven
            - tmux
            - postgresql
            - redis
            - cocoapods
            - jq 
            - watchman
            - rbenv
            - nvm
            - docker
            - ansible
            - hugo
            - docker-compose
            - rust
            - erlang
            - elixir
            - git
            - rsync
            - curl
            - wget
            - tree
            - httpie
            - kubectl
            - kubernetes-helm
            - zsh
            - go
            - python
            - ruby
            - nodejs
            - yarn
            - vim
            - terraform
        - cask_applications:
            - java
            - docker
            - iterm2
            - google-chrome
            - firefox
            - visual-studio-code
            - slack
            - vlc
            - fastlane
            - spotify
            - rstudio
            - aws-vault
            - google-cloud-sdk
            - skype
            - react-native-debugger
            - gimp
            - ngrok
            - mactex
            - microsoft-office
            - android-studio
            - discord
            - github
            - jetbrains-toolbox
            - calibre
            - anki
            - transmission
            - microsoft-teams
            - whatsapp
            - pgadmin4
            - onedrive
  tasks:
      - name: install homebrew
        shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"' 
        args:
            creates: /usr/local/bin/brew

      - name: ensure homebrew is updated 
        homebrew:
            state: latest
            update_homebrew: yes

      - name: tap homebrew caskroom/cask
        homebrew_tap:
            tap: "caskroom/cask"

      - name: start installing homebrew applications
        homebrew:
            name: "{{applications}}"
            state: latest
 
      - name: start installing homebrew cask applications
        homebrew_cask:
            name: "{{cask_applications}}"
            state: installed 